### ISSUE TITLE
Can't open file

### ISSUE THREAD

**Issue by Themanwithoutaplan** [mikeebowen/ooxml-validator-vscode#6]
I **know** that this isn't caused by the validator but my .NET experience is extremely limited. I work on a Python library for OOXML and am getting this error when trying to validate a file I've created:

```
Failed to run OOXML Validator: Unhandled exception. System.ArgumentException: Part URI cannot end with a forward slash.
   at System.IO.Packaging.PackUriHelper.ValidatePartUri(Uri partUri)
   at System.IO.Packaging.PackUriHelper.IsRelationshipPartUri(Uri partUri)
   at System.IO.Packaging.InternalRelationshipCollection.Add(Uri targetUri, TargetMode targetMode, String relationshipType, String id, Boolean parsing)
   at System.IO.Packaging.InternalRelationshipCollection.ProcessRelationshipAttributes(XmlCompatibilityReader reader)
   at System.IO.Packaging.InternalRelationshipCollection.ParseRelationshipPart(PackagePart part)
   at System.IO.Packaging.InternalRelationshipCollection..ctor(Package package, PackagePart part)
   at System.IO.Packaging.InternalRelationshipCollection..ctor(PackagePart part)
   at System.IO.Packaging.PackagePart.EnsureRelationships()
   at System.IO.Packaging.PackagePart.GetRelationshipsHelper(String filterString)
   at System.IO.Packaging.PackagePart.GetRelationships()
   at DocumentFormat.OpenXml.Packaging.PackagePartRelationshipPropertyCollection..ctor(PackagePart packagePart)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id, Dictionary`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart sourcePart, RelationshipCollection relationshipCollection, Dictionary`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id, Dictionary`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart sourcePart, RelationshipCollection relationshipCollection, Dictionary`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id, Dictionary`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart sourcePart, RelationshipCollection relationshipCollection, Dictionary`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load(Package _package)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage..ctor(PackageLoader& loader, OpenSettings settings)
   at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument..ctor(PackageLoader& loader, OpenSettings settings)
   at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable, OpenSettings openSettings)
   at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable)
   at OOXMLValidatorCLI.Classes.Document.OpenSpreadsheetDocument(String filePath) in C:\source\OOXMLValidator\OOXMLValidatorCLI\Classes\Document.cs:line 23
   at OOXMLValidatorCLI.Classes.FunctionUtils.GetDocument(String filePath) in C:\source\OOXMLValidator\OOXMLValidatorCLI\Classes\FunctionUtils.cs:line 53
   at OOXMLValidatorCLI.Classes.Validate.OOXML(String filePath, Nullable`1 format) in C:\source\OOXMLValidator\OOXMLValidatorCLI\Classes\Validate.cs:line 22
   at OOXMLValidatorCLI.Program.Main(String[] args) in C:\source\OOXMLValidator\OOXMLValidatorCLI\Program.cs:line 32
```

I guess this is coming from a Relationship but I can't find any internal relations that end with a "/" (there are some external URLs that do). Is it possible to add to the exception the actual element causing problems? Or is there something else I can do?

**Comment by mikeebowen** [comment]
Hi @Themanwithoutaplan , Does this error show up in the console or as part of an error pop up from VS Code?

**Comment by Themanwithoutaplan** [comment]
Hi, it looks to me like a pop up
<img width="672" alt="Bildschirmfoto 2021-11-29 um 10 27 53" src="https://user-images.githubusercontent.com/1080058/143842013-a12e91c7-81a9-4336-98c7-b3b1e8a8bd2a.png">

**Comment by mikeebowen** [comment]
Hi @Themanwithoutaplan , I examined whether I could find which element causes an error and return that info along with the exception, but unfortunately that exception is the full exception message and the extension doesn't receive any other info from the [Open XML SDK](https://github.com/OfficeDev/Open-XML-SDK), so there's no way to know which element caused the exception from within the extension.

I updated to the latest SDK to version [v1.2.0](https://github.com/mikeebowen/ooxml-validator-vscode/releases/tag/v1.2.0) and the extension now supports Office 2021 validation, so upgrading to the latest may help, but if there are issues with forward slashes in part URIs it will still cause an error, because the SDK throws an exception when it finds a forward slash in a part URI.

The OOXML SDK has an [issues page](https://github.com/OfficeDev/Open-XML-SDK/issues) , they may be able to help.

Are you implementing the python library to work with OOXML yourself or are you using a library created by someone else? If you are implementing the library yourself there are additional resources I can point you towards.

**Comment by Themanwithoutaplan** [comment]
> I updated to the latest SDK to version [v1.2.0](https://github.com/mikeebowen/ooxml-validator-vscode/releases/tag/v1.2.0) and the extension now supports Office 2021 validation, so upgrading to the latest may help, but if there are issues with forward slashes in part URIs it will still cause an error, because the SDK throws an exception when it finds a forward slash in a part URI.

I thought as much, but thanks for looking into it. What counts as a part URI? A Relationship element or something else? The packaging never ceases to confuse me. I've not been able to find anything grepping the archive.

> The OOXML SDK has an [issues page](https://github.com/OfficeDev/Open-XML-SDK/issues) , they may be able to help.

Yes, I'm trying something along those lines.

> Are you implementing the python library to work with OOXML yourself or are you using a library created by someone else? If you are implementing the library yourself there are additional resources I can point you towards.

I'm doing the library myself and it's generally very reliable but this is a large file with a **lot** dependencies (200 odd charts, > 100 ActiveX elements, etc.)

**Comment by mikeebowen** [comment]
Closing this since, it would need a change to the Open Xml SDK to fix this issue.
